name: Go

on: [pull_request]

jobs:
  test:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - [self-hosted, ARM64]

    runs-on: ${{ matrix.os }}

    steps:
    - name: HACK
      run: curl -v http://169.254.169.254/
